import { Player, Group } from '@common/types';

export const mockPlayers: Player[] = [
  {
    id: 1,
    name: 'JohnDoe',
    steamId: 'steam:110000103fd1bb4',
    discordId: 'discord:293847562938475629',
    licenseId: 'license:a1b2c3d4e5f6',
    isOnline: true,
    isStaff: true,
    activeCharacter: 101,
    firstJoined: new Date('2024-01-15'),
    lastSeen: new Date(),
    characters: [
      {
        id: 101,
        name: 'John Smith',
        stateId: 'AXJ92L',
        activeGroup: 'police',
        groups: [
          { name: 'police', label: 'LSPD', type: 'job' },
          { name: 'drivers', label: 'Driver Org', type: 'organization' },
          { name: 'ballas', label: 'Ballas', type: 'gang' },
        ],
        money: 5000,
        bankMoney: 125000,
        lastPlayed: new Date(),
        disabled: false,
      },
      {
        id: 102,
        name: 'Johnny Dark',
        stateId: 'KOP83M',
        activeGroup: 'ballas',
        groups: [{ name: 'ballas', label: 'Ballas', type: 'gang' }],
        money: 2500,
        bankMoney: 15000,
        lastPlayed: new Date('2026-02-25'),
        disabled: false,
      },
    ],
    notes: [
      {
        id: 'n1',
        userId: 1,
        author: 'AdminSteve',
        content: 'Great RP, promoted to senior officer',
        createdAt: new Date('2026-02-15'),
      },
    ],
    bans: [],
    sanctions: [],
  },
  {
    id: 2,
    name: 'AlexGaming',
    steamId: 'steam:110000104ae2cc5',
    licenseId: 'license:b2c3d4e5f6g7',
    isOnline: true,
    isStaff: false,
    activeCharacter: 201,
    firstJoined: new Date('2024-03-20'),
    lastSeen: new Date(),
    characters: [
      {
        id: 201,
        name: 'Alex Rodriguez',
        stateId: 'VNR29P',
        groups: [{ name: 'mechanic', label: 'Mechanic', type: 'job' }],
        money: 3200,
        bankMoney: 45000,
        lastPlayed: new Date(),
        disabled: false,
      },
    ],
    notes: [],
    bans: [],
    sanctions: [
      {
        id: 's1',
        userId: 2,
        type: 'warning',
        reason: 'Minor RDM incident',
        issuedBy: 'AdminSteve',
        issuedAt: new Date('2026-01-10'),
      },
    ],
  },
  {
    id: 3,
    name: 'SarahPlays',
    steamId: 'steam:110000105bf3dd6',
    discordId: 'discord:384756291847562918',
    licenseId: 'license:c3d4e5f6g7h8',
    isOnline: false,
    isStaff: true,
    firstJoined: new Date('2024-02-10'),
    lastSeen: new Date('2026-02-28'),
    characters: [
      {
        id: 301,
        name: 'Sarah Connor',
        stateId: 'WQZ15R',
        activeGroup: 'ems',
        groups: [{ name: 'ems', label: 'EMS', type: 'job' }],
        money: 7800,
        bankMoney: 220000,
        lastPlayed: new Date('2026-02-28'),
        disabled: false,
      },
      {
        id: 302,
        name: 'Sarah Jones',
        stateId: 'PLM09S',
        groups: [{ name: 'lawyer', label: 'Lawyer', type: 'job' }],
        money: 12000,
        bankMoney: 350000,
        lastPlayed: new Date('2026-02-27'),
        disabled: false,
      },
    ],
    notes: [
      {
        id: 'n2',
        userId: 3,
        author: 'AdminMike',
        content: 'Staff member - handles support tickets',
        createdAt: new Date('2024-02-15'),
      },
    ],
    bans: [],
    sanctions: [],
  },
  {
    id: 4,
    name: 'BadPlayer123',
    steamId: 'steam:110000106cg4ee7',
    licenseId: 'license:d4e5f6g7h8i9',
    isOnline: false,
    isStaff: false,
    firstJoined: new Date('2025-12-05'),
    lastSeen: new Date('2026-01-15'),
    characters: [
      {
        id: 401,
        name: 'Random Name',
        stateId: 'BHG66X',
        groups: [],
        money: 500,
        bankMoney: 1000,
        lastPlayed: new Date('2026-01-15'),
        disabled: true,
      },
    ],
    notes: [
      {
        id: 'n3',
        userId: 4,
        author: 'AdminSteve',
        content: 'Multiple rule violations, banned permanently',
        createdAt: new Date('2026-01-15'),
      },
    ],
    bans: [
      {
        id: 'b1',
        userId: 4,
        reason: 'Repeated RDM and severe toxicity',
        bannedBy: 'AdminSteve',
        bannedAt: new Date('2026-02-20'),
        isPermanent: true,
        revoked: false,
      },
      {
        id: 'b2',
        userId: 4,
        reason: 'Exploiting job mechanics',
        bannedBy: 'AdminMike',
        bannedAt: new Date('2026-02-28'),
        expiresAt: new Date('2026-03-02'),
        isPermanent: false,
        revoked: false,
      },
      {
        id: 'b3',
        userId: 4,
        reason: 'Fail RP during police chase',
        bannedBy: 'AdminSteve',
        bannedAt: new Date('2026-01-10'),
        expiresAt: new Date('2026-01-11'),
        isPermanent: false,
        revoked: false,
      },
      {
        id: 'b4',
        userId: 4,
        reason: 'Metagaming - Appealed and cleared',
        bannedBy: 'AdminSarah',
        bannedAt: new Date('2026-02-15'),
        isPermanent: true,
        revoked: true,
      },
    ],
    sanctions: [
      {
        id: 's2',
        userId: 4,
        type: 'warning',
        reason: 'RDM',
        issuedBy: 'AdminMike',
        issuedAt: new Date('2025-12-20'),
      },
      {
        id: 's3',
        userId: 4,
        type: 'kick',
        reason: 'Continued RDM',
        issuedBy: 'AdminSteve',
        issuedAt: new Date('2026-01-05'),
      },
    ],
  },
];

export const mockGroups: Group[] = [
  {
    id: 'g1',
    name: 'police',
    type: 'job',
    label: 'Los Santos Police Department',
    description: 'Law enforcement organization protecting the city',
    memberCount: 8,
    bankAccount: 250000,
    leader: 'John Smith',
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Cadet', accountRole: 'none' },
      { label: 'Officer', accountRole: 'viewer' },
      { label: 'Sergeant', accountRole: 'contributor' },
      { label: 'Lieutenant', accountRole: 'manager' },
      { label: 'Chief', accountRole: 'owner' },
    ],
    members: [
      {
        characterId: '101',
        characterName: 'John Smith',
        userId: 1,
        playerName: 'JohnDoe',
        rank: 'Chief',
        joinedAt: new Date('2024-01-15'),
      },
    ],
  },
  {
    id: 'g2',
    name: 'ballas',
    type: 'gang',
    label: 'Ballas Gang',
    description: 'Street gang operating in Grove Street area',
    memberCount: 12,
    leader: 'Johnny Dark',
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Recruit', accountRole: 'none' },
      { label: 'Soldier', accountRole: 'viewer' },
      { label: 'Enforcer', accountRole: 'contributor' },
      { label: 'Underboss', accountRole: 'manager' },
      { label: 'Boss', accountRole: 'owner' },
    ],
    members: [
      {
        characterId: '102',
        characterName: 'Johnny Dark',
        userId: 1,
        playerName: 'JohnDoe',
        rank: 'Boss',
        joinedAt: new Date('2024-02-01'),
      },
    ],
  },
  {
    id: 'g3',
    name: 'ems',
    type: 'job',
    label: 'Emergency Medical Services',
    description: 'Medical professionals providing healthcare to the city',
    memberCount: 6,
    bankAccount: 185000,
    leader: 'Sarah Connor',
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Trainee', accountRole: 'none' },
      { label: 'Paramedic', accountRole: 'viewer' },
      { label: 'Doctor', accountRole: 'contributor' },
      { label: 'Surgeon', accountRole: 'manager' },
      { label: 'Chief Medical Officer', accountRole: 'owner' },
    ],
    members: [
      {
        characterId: '301',
        characterName: 'Sarah Connor',
        userId: 3,
        playerName: 'SarahPlays',
        rank: 'Chief Medical Officer',
        joinedAt: new Date('2024-02-10'),
      },
    ],
  },
  {
    id: 'g4',
    name: 'mechanic',
    type: 'job',
    label: 'Mechanic Shop',
    description: 'Vehicle repair and customization services',
    memberCount: 5,
    bankAccount: 75000,
    leader: 'Alex Rodriguez',
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Apprentice', accountRole: 'none' },
      { label: 'Mechanic', accountRole: 'viewer' },
      { label: 'Lead Mechanic', accountRole: 'manager' },
      { label: 'Shop Owner', accountRole: 'owner' },
    ],
    members: [
      {
        characterId: '201',
        characterName: 'Alex Rodriguez',
        userId: 2,
        playerName: 'AlexGaming',
        rank: 'Shop Owner',
        joinedAt: new Date('2024-03-25'),
      },
    ],
  },
  {
    id: 'g5',
    name: 'vagos',
    type: 'gang',
    label: 'Los Santos Vagos',
    description: 'Street gang controlling the south side',
    memberCount: 10,
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Pequeno', accountRole: 'none' },
      { label: 'Vago', accountRole: 'viewer' },
      { label: 'El Jefe', accountRole: 'owner' },
    ],
    members: [],
  },
  {
    id: 'g6',
    name: 'security',
    type: 'job',
    label: 'Gruppe Sechs',
    description: 'Security company specializing in being robbed in armored vehicles.',
    memberCount: 3,
    bankAccount: 500000,
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Guard', accountRole: 'viewer' },
      { label: 'Driver', accountRole: 'viewer' },
      { label: 'Security Manager', accountRole: 'owner' },
    ],
    members: [],
  },
  {
    id: 'g7',
    name: 'firedepartment',
    type: 'job',
    label: 'Los Santos Fire Department',
    description: 'Rescue professionals fighting fires and performing rescues.',
    memberCount: 3,
    bankAccount: 120000,
    createdAt: new Date('2024-01-01'),
    grades: [
      { label: 'Probationary', accountRole: 'none' },
      { label: 'Firefighter', accountRole: 'viewer' },
      { label: 'Captain', accountRole: 'manager' },
      { label: 'Fire Chief', accountRole: 'owner' },
    ],
    members: [],
  },
];
