import { Player, Group, Character } from '../types';

export const mockPlayers: Player[] = [
  {
    id: 'p1',
    name: 'JohnDoe',
    steamId: 'steam:110000103fd1bb4',
    discordId: 'discord:293847562938475629',
    licenseId: 'license:a1b2c3d4e5f6',
    isOnline: true,
    isStaff: true,
    firstJoined: new Date('2024-01-15'),
    lastSeen: new Date(),
    characters: [
      {
        id: 'c1',
        name: 'John Smith',
        playerId: 'p1',
        identifier: 'char:p1c1',
        job: 'police',
        money: 5000,
        bankMoney: 125000,
        lastPlayed: new Date(),
        disabled: false,
      },
      {
        id: 'c2',
        name: 'Johnny Dark',
        playerId: 'p1',
        identifier: 'char:p1c2',
        job: 'unemployed',
        gang: 'ballas',
        money: 2500,
        bankMoney: 15000,
        lastPlayed: new Date('2026-02-25'),
        disabled: false,
      },
    ],
    notes: [
      {
        id: 'n1',
        playerId: 'p1',
        author: 'AdminSteve',
        content: 'Great RP, promoted to senior officer',
        createdAt: new Date('2026-02-15'),
      },
    ],
    bans: [],
    sanctions: [],
  },
  {
    id: 'p2',
    name: 'AlexGaming',
    steamId: 'steam:110000104ae2cc5',
    licenseId: 'license:b2c3d4e5f6g7',
    isOnline: true,
    isStaff: false,
    firstJoined: new Date('2024-03-20'),
    lastSeen: new Date(),
    characters: [
      {
        id: 'c3',
        name: 'Alex Rodriguez',
        playerId: 'p2',
        identifier: 'char:p2c1',
        job: 'mechanic',
        money: 3200,
        bankMoney: 45000,
        lastPlayed: new Date(),
        disabled: false,
      },
    ],
    notes: [],
    bans: [],
    sanctions: [
      {
        id: 's1',
        playerId: 'p2',
        type: 'warning',
        reason: 'Minor RDM incident',
        issuedBy: 'AdminSteve',
        issuedAt: new Date('2026-01-10'),
      },
    ],
  },
  {
    id: 'p3',
    name: 'SarahPlays',
    steamId: 'steam:110000105bf3dd6',
    discordId: 'discord:384756291847562918',
    licenseId: 'license:c3d4e5f6g7h8',
    isOnline: false,
    isStaff: true,
    firstJoined: new Date('2024-02-10'),
    lastSeen: new Date('2026-02-28'),
    characters: [
      {
        id: 'c4',
        name: 'Sarah Connor',
        playerId: 'p3',
        identifier: 'char:p3c1',
        job: 'doctor',
        money: 7800,
        bankMoney: 220000,
        lastPlayed: new Date('2026-02-28'),
        disabled: false,
      },
      {
        id: 'c5',
        name: 'Sarah Jones',
        playerId: 'p3',
        identifier: 'char:p3c2',
        job: 'lawyer',
        money: 12000,
        bankMoney: 350000,
        lastPlayed: new Date('2026-02-27'),
        disabled: false,
      },
    ],
    notes: [
      {
        id: 'n2',
        playerId: 'p3',
        author: 'AdminMike',
        content: 'Staff member - handles support tickets',
        createdAt: new Date('2024-02-15'),
      },
    ],
    bans: [],
    sanctions: [],
  },
  {
    id: 'p4',
    name: 'BadPlayer123',
    steamId: 'steam:110000106cg4ee7',
    licenseId: 'license:d4e5f6g7h8i9',
    isOnline: false,
    isStaff: false,
    firstJoined: new Date('2025-12-05'),
    lastSeen: new Date('2026-01-15'),
    characters: [
      {
        id: 'c6',
        name: 'Random Name',
        playerId: 'p4',
        identifier: 'char:p4c1',
        job: 'unemployed',
        money: 500,
        bankMoney: 1000,
        lastPlayed: new Date('2026-01-15'),
        disabled: true,
      },
    ],
    notes: [
      {
        id: 'n3',
        playerId: 'p4',
        author: 'AdminSteve',
        content: 'Multiple rule violations, banned permanently',
        createdAt: new Date('2026-01-15'),
      },
    ],
    bans: [
      {
        id: 'b1',
        playerId: 'p4',
        reason: 'Repeated RDM, toxicity, fail RP',
        bannedBy: 'AdminSteve',
        bannedAt: new Date('2026-01-15'),
        isPermanent: true,
        isActive: true,
      },
    ],
    sanctions: [
      {
        id: 's2',
        playerId: 'p4',
        type: 'warning',
        reason: 'RDM',
        issuedBy: 'AdminMike',
        issuedAt: new Date('2025-12-20'),
      },
      {
        id: 's3',
        playerId: 'p4',
        type: 'kick',
        reason: 'Continued RDM',
        issuedBy: 'AdminSteve',
        issuedAt: new Date('2026-01-05'),
      },
    ],
  },
  {
    id: 'p5',
    name: 'MikeRP',
    steamId: 'steam:110000107dh5ff8',
    licenseId: 'license:e5f6g7h8i9j0',
    isOnline: true,
    isStaff: false,
    firstJoined: new Date('2024-06-12'),
    lastSeen: new Date(),
    characters: [
      {
        id: 'c7',
        name: 'Mike Johnson',
        playerId: 'p5',
        identifier: 'char:p5c1',
        job: 'taxi',
        money: 1800,
        bankMoney: 32000,
        lastPlayed: new Date(),
        disabled: false,
      },
    ],
    notes: [],
    bans: [],
    sanctions: [],
  },
  {
    id: 'p6',
    name: 'Yeet',
    steamId: 'steam:110000107dh5ff8',
    licenseId: 'license:e5f6g7h8i9j0',
    isOnline: true,
    isStaff: false,
    firstJoined: new Date('2020-06-12'),
    lastSeen: new Date(),
    characters: [
      {
        id: 'c8',
        name: 'Some Random Dev',
        playerId: 'p6',
        identifier: 'char:p6c1',
        job: 'unemployed',
        money: 2000,
        bankMoney: 32000,
        lastPlayed: new Date(),
        disabled: false,
      },
    ],
    notes: [],
    bans: [],
    sanctions: [],
  },
];

export const mockGroups: Group[] = [
  {
    id: 'g1',
    name: 'police',
    type: 'job',
    label: 'Los Santos Police Department',
    description: 'Law enforcement organization protecting the city',
    memberCount: 8,
    leader: 'John Smith',
    createdAt: new Date('2024-01-01'),
    members: [
      {
        characterId: 'c1',
        characterName: 'John Smith',
        playerId: 'p1',
        playerName: 'JohnDoe',
        rank: 'Chief',
        joinedAt: new Date('2024-01-15'),
      },
    ],
  },
  {
    id: 'g2',
    name: 'ballas',
    type: 'gang',
    label: 'Ballas Gang',
    description: 'Street gang operating in Grove Street area',
    memberCount: 12,
    leader: 'Johnny Dark',
    createdAt: new Date('2024-01-01'),
    members: [
      {
        characterId: 'c2',
        characterName: 'Johnny Dark',
        playerId: 'p1',
        playerName: 'JohnDoe',
        rank: 'Boss',
        joinedAt: new Date('2024-02-01'),
      },
    ],
  },
  {
    id: 'g3',
    name: 'ems',
    type: 'job',
    label: 'Emergency Medical Services',
    description: 'Medical professionals providing healthcare to the city',
    memberCount: 6,
    leader: 'Sarah Connor',
    createdAt: new Date('2024-01-01'),
    members: [
      {
        characterId: 'c4',
        characterName: 'Sarah Connor',
        playerId: 'p3',
        playerName: 'SarahPlays',
        rank: 'Chief Medical Officer',
        joinedAt: new Date('2024-02-10'),
      },
    ],
  },
  {
    id: 'g4',
    name: 'mechanic',
    type: 'job',
    label: 'Mechanic Shop',
    description: 'Vehicle repair and customization services',
    memberCount: 5,
    leader: 'Alex Rodriguez',
    createdAt: new Date('2024-01-01'),
    members: [
      {
        characterId: 'c3',
        characterName: 'Alex Rodriguez',
        playerId: 'p2',
        playerName: 'AlexGaming',
        rank: 'Shop Owner',
        joinedAt: new Date('2024-03-25'),
      },
    ],
  },
  {
    id: 'g5',
    name: 'vagos',
    type: 'gang',
    label: 'Los Santos Vagos',
    description: 'Street gang controlling the south side',
    memberCount: 10,
    createdAt: new Date('2024-01-01'),
    members: [],
  },
];
